apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscaler-config
  namespace: default
data:
  TARGET_UTILIZATION: "0.7"
  MIN_REPLICAS: "1"
  MAX_REPLICAS: "10"
  SCALE_UP_COOLDOWN: "30"
  SCALE_DOWN_COOLDOWN: "180"
  POLL_INTERVAL: "15"
  DEPLOYMENT: "ml-replica"
  NAMESPACE: "default"
  PROMETHEUS_URL: "http://prometheus-kube-prometheus-prometheus.default.svc.cluster.local:9090"
